import React from 'react';
import ReactDOM from 'react-dom';
import Comparator from "./Comparator";

ReactDOM.render(
	<>
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}
		{/*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a bibendum erat, ut viverra turpis. Pellentesque lacinia, sem ut ultricies tincidunt, dolor purus finibus lacus, vitae tristique quam lorem rutrum lectus. Praesent feugiat rhoncus mi in laoreet. Vestibulum tincidunt, mi a pharetra volutpat, turpis tellus condimentum purus, quis aliquam odio arcu id mi. Mauris quis viverra nisl. Proin ac aliquet enim. Sed porttitor dui at odio varius laoreet. Maecenas facilisis nunc eros, non suscipit mauris egestas ac. Curabitur molestie lorem eu mi scelerisque feugiat. Nulla ut accumsan metus. Morbi tincidunt nulla eget laoreet pulvinar. Ut ut nibh non erat viverra dapibus. Aenean consequat euismod auctor. Phasellus a egestas nulla.</p>*/}

		<Comparator />
	</>,
  document.getElementById('root')
);
